### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by PuneetP16**

### CODE REVIEW

**Review by muskanbagrecha — APPROVED** [review]
1. Add price slider in filter
Looks good overall.

**Comment by muskanbagrecha** [comment]
Mention about dark theme and light theme.

**Comment by PuneetP16** [comment]
> Mention about dark theme and light theme.

Done thanks for mentioning this, I completely forgot to add that.

**Comment by PuneetP16** [comment]
> 1. Add price slider in filter
>    Looks good overall.

Done.

**Comment by sushmita12345** [comment]
Good to merge.

**Review by sushmita12345 — APPROVED** [review]

**Review by m26unkwn — APPROVED** [review]
Great README File.

**Pull request merged**
